function inverted_vars = invert_warp_vars(vars)
div = (1 + vars(1)) * (1 + vars(4)) - vars(2) * vars(3);
inverted_vars = [-vars(1) - vars(1)*vars(4) + vars(2) * vars(3) ...
                 -vars(2) ...
                 -vars(3) ...
                 -vars(4) - vars(1)*vars(4) + vars(2) * vars(3) ...
                 -vars(5) - vars(4)*vars(5) + vars(3) * vars(6) ...
                 -vars(6) - vars(1)*vars(6) + vars(2) * vars(5) ...
                 ] / div;

end

